-- MODULO: BASE DE DATOS
-- TAREA PARA BD06
-- ALUMNO: NELSON BLANCO CHARRO

----- ACTIVIDAD 1: FUNCION TOTAL_PEDIDO -----
--FUNCION
CREATE OR REPLACE FUNCTION F_TOTAL_PEDIDO 
    (P_IDPEDIDO IN E_DETALLEPEDIDOS.IDPEDIDO%TYPE) 
    RETURN NUMBER 
IS
    TOTAL_PEDIDO NUMBER := 0;
    CURSOR C IS
        SELECT UNIDADESPEDIDAS, IDPRODUCTO FROM E_DETALLEPEDIDOS WHERE IDPEDIDO=P_IDPEDIDO;
    V_PRECIOVENTA NUMBER;
    V_DESCUENTO NUMBER(4,2);
BEGIN
    FOR VC IN C LOOP
        SELECT PRECIOVENTA INTO V_PRECIOVENTA FROM E_PRODUCTOS WHERE IDPRODUCTO=VC.IDPRODUCTO;
        TOTAL_PEDIDO := TOTAL_PEDIDO + VC.UNIDADESPEDIDAS * V_PRECIOVENTA;
    END LOOP;
    IF TOTAL_PEDIDO > 50001 THEN V_DESCUENTO := 0.1;
        ELSIF TOTAL_PEDIDO BETWEEN 20001 AND 50000 THEN V_DESCUENTO := 0.05;
        ELSE V_DESCUENTO := 0;
    END IF;
    TOTAL_PEDIDO := TOTAL_PEDIDO - TOTAL_PEDIDO * V_DESCUENTO;
    RETURN TOTAL_PEDIDO;
END F_TOTAL_PEDIDO;

--SENTENCIA
DECLARE
    V_TOTALPEDIDO NUMBER;
    V_IDPEDIDO NUMBER := 1;
BEGIN
    V_TOTALPEDIDO := F_TOTAL_PEDIDO(V_IDPEDIDO);
    dbms_output.put_line('El pedido total es de: '||V_TOTALPEDIDO);
END;


----- ACTIVIDAD 2: FUNCION EXISTE_CLIENTE -----
--FUNCION
CREATE OR REPLACE FUNCTION F_EXISTE_CLIENTE 
    (P_IDCLIENTE IN E_CLIENTES.IDCLIENTE%TYPE)
    RETURN BOOLEAN
IS 
    V_IDCLIENTE NUMBER;
BEGIN
    SELECT IDCLIENTE INTO V_IDCLIENTE FROM E_CLIENTES WHERE IDCLIENTE=P_IDCLIENTE;
    RETURN TRUE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN FALSE;
END F_EXISTE_CLIENTE;

--SENTENCIA
DECLARE
    V_IDCLIENTE NUMBER := 1;
BEGIN
    IF F_EXISTE_CLIENTE(V_IDCLIENTE) THEN dbms_output.put_line('El cliente existe');
        ELSE dbms_output.put_line('El cliente NO existe');
    END IF;
END;


----- ACTIVIDAD 3: PROCEDIMIENTO TOTAL_CLIENTE -----
--PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE P_TOTAL_CLIENTE (
    P_IDCLIENTE         IN      E_CLIENTES.IDCLIENTE%TYPE,
    P_ANIO              IN      VARCHAR2,
    P_TOTAL_CLIENTE     OUT     NUMBER)
AS 
    CURSOR C IS
        SELECT IDPEDIDO, FECHAENTREGA, FECHAESPERADA
        FROM E_PEDIDOS 
        WHERE 
            ESTADOENVIO = 'E' 
            AND PEDIDOPAGADO = 'S'
            -- TENEMOS QUE CAMBIAR EL TIPO DEL AÑO A NUMERO
            AND EXTRACT(YEAR FROM FECHAPEDIDO) = TO_NUMBER(P_ANIO)
            AND IDCLIENTE = P_IDCLIENTE;
    NO_EXISTE_CLIENTE EXCEPTION;
    NO_HAY_CLIENTES_CURSOR EXCEPTION;
    V_TOTAL_CLIENTE NUMBER := 0;
    V_DESCUENTO NUMBER;
    VC C%ROWTYPE;
BEGIN
    IF NOT F_EXISTE_CLIENTE(P_IDCLIENTE) 
        THEN RAISE NO_EXISTE_CLIENTE;
    ELSE
        OPEN C;
        FETCH C INTO VC;
        IF C%NOTFOUND THEN
            RAISE NO_HAY_CLIENTES_CURSOR;
        ELSE WHILE C%FOUND LOOP
            IF VC.FECHAENTREGA > VC.FECHAESPERADA  THEN V_DESCUENTO := 0.01;
            ELSE V_DESCUENTO := 0;
            END IF;
            V_TOTAL_CLIENTE := V_TOTAL_CLIENTE + (F_TOTAL_PEDIDO(VC.IDPEDIDO) - F_TOTAL_PEDIDO(VC.IDPEDIDO) * V_DESCUENTO);
            FETCH C INTO VC;
        END LOOP;
        P_TOTAL_CLIENTE := V_TOTAL_CLIENTE;
        END IF;
    CLOSE C;
    END IF;
EXCEPTION
    WHEN NO_EXISTE_CLIENTE THEN P_TOTAL_CLIENTE := -1;
    WHEN NO_HAY_CLIENTES_CURSOR THEN P_TOTAL_CLIENTE := -2;
END P_TOTAL_CLIENTE;

--SENTENCIA
DECLARE
    V_IDCLIENTE NUMBER := 2;
    V_ANIO VARCHAR2(4) := '2022';
    V_TOTAL_CLIENTE NUMBER;
BEGIN
    P_TOTAL_CLIENTE(V_IDCLIENTE, V_ANIO, V_TOTAL_CLIENTE);
    IF V_TOTAL_CLIENTE = -1 THEN dbms_output.put_line('NO EXISTE EL CLIENTE');
        ELSIF V_TOTAL_CLIENTE = -2 THEN dbms_output.put_line('EL CLIENTE NO TIENE PEDIDIOS ESE ANIO');
        ELSE dbms_output.put_line('EL CLIENTE '||V_IDCLIENTE||' TIENE UN TOTAL DE: '||V_TOTAL_CLIENTE||'E');
    END IF;
END;

