--CICLO : DESARROLLO APLICACIONES WEB
--MÓDULO : BASE DE DATOS
--ALUMNO : NELSON BLANCO CHARRO
--TAREA : BD07


----- APARTADO 1
CREATE OR REPLACE TYPE PERSONAL AS OBJECT (
    IDCLIENTE NUMBER(5),
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(30),
    CALLE VARCHAR2(100),
    POBLACION VARCHAR2(50),
    PROVINCIA VARCHAR2(30),
    FECHA_ALTA DATE
) NOT FINAL;


----- APARTADO 2
CREATE OR REPLACE TYPE CLIENTE UNDER PERSONAL(
    NRO_CUENTA VARCHAR2(20),
    TIPO_CLI NUMBER(1),
    -- Primer constructor
    CONSTRUCTOR FUNCTION CLIENTE(P_IDCLIENTE NUMBER,P_DNI VARCHAR2, P_NOMBRE VARCHAR2, P_APELLIDOS VARCHAR2, P_CALLE VARCHAR2, P_POBLACION VARCHAR2, P_PROVINCIA VARCHAR2)
        RETURN SELF AS RESULT,
    -- Segundo constructor
    CONSTRUCTOR FUNCTION CLIENTE(P_IDCLIENTE NUMBER, P_DNI VARCHAR2, P_NOMBRE VARCHAR2, P_CALLE VARCHAR2, P_POBLACION VARCHAR2, P_PROVINCIA VARCHAR2, P_FECHA_ALTA DATE)
        RETURN SELF AS RESULT,
    -- Metodo getDireccion
    MEMBER FUNCTION GETDIRECCION RETURN VARCHAR2,
    -- Metodos setter
    MEMBER PROCEDURE SETIDCLIENTE(IDCLIENTE NUMBER),
    MEMBER PROCEDURE SETDNI(DNI VARCHAR2),
    MEMBER PROCEDURE SETNOMBRE(NOMBRE VARCHAR2, APELLIDO VARCHAR2),
    MEMBER PROCEDURE SETNOMBRE(NOMBRE VARCHAR2),
    MEMBER PROCEDURE SETCALLE(CALLE VARCHAR2),
    MEMBER PROCEDURE SETPOBLACION(POBLACION VARCHAR2),
    MEMBER PROCEDURE SETPROVINCIA(PROVINCIA VARCHAR2),
    MEMBER PROCEDURE SETFECHALTA(FECHA NUMBER),
    MEMBER PROCEDURE SETFECHALTA(FECHA_ALTA DATE)
);
    --Creacion del body
CREATE OR REPLACE TYPE BODY CLIENTE AS
    -- Primer constructor
    CONSTRUCTOR FUNCTION CLIENTE(P_IDCLIENTE NUMBER,P_DNI VARCHAR2, P_NOMBRE VARCHAR2, P_APELLIDOS VARCHAR2, P_CALLE VARCHAR2, P_POBLACION VARCHAR2, P_PROVINCIA VARCHAR2)
    RETURN SELF AS RESULT AS
        BEGIN
            SELF.SETIDCLIENTE(P_IDCLIENTE);
            SELF.SETDNI(P_DNI);
            SELF.SETNOMBRE(P_NOMBRE, P_APELLIDOS);
            SELF.SETCALLE(P_CALLE); 
            SELF.SETPOBLACION(P_POBLACION); 
            SELF.SETPROVINCIA(P_PROVINCIA); 
            SELF.SETFECHALTA(0); 
        RETURN;
    END CLIENTE;
    -- Segundo constructor
    CONSTRUCTOR FUNCTION CLIENTE(P_IDCLIENTE NUMBER, P_DNI VARCHAR2, P_NOMBRE VARCHAR2, P_CALLE VARCHAR2, P_POBLACION VARCHAR2, P_PROVINCIA VARCHAR2, P_FECHA_ALTA DATE)
    RETURN SELF AS RESULT AS
        BEGIN
            SELF.SETIDCLIENTE(P_IDCLIENTE);
            SELF.SETDNI(P_DNI);
            SELF.SETNOMBRE(P_NOMBRE);
            SELF.SETCALLE(P_CALLE); 
            SELF.SETPOBLACION(P_POBLACION); 
            SELF.SETPROVINCIA(P_PROVINCIA); 
            SELF.SETFECHALTA(P_FECHA_ALTA); 
        RETURN;
    END CLIENTE;
    -- Metodo getDireccion
    MEMBER FUNCTION GETDIRECCION RETURN VARCHAR2 AS
        BEGIN
        RETURN (SELF.CALLE||SELF.POBLACION||SELF.PROVINCIA);
    END GETDIRECCION;
    -- Metodos setter
    MEMBER PROCEDURE SETIDCLIENTE(IDCLIENTE NUMBER) AS
        BEGIN
        SELF.IDCLIENTE:=IDCLIENTE;
    END SETIDCLIENTE;
    MEMBER PROCEDURE SETDNI(DNI VARCHAR2) AS
        BEGIN
        SELF.DNI:=DNI;
    END SETDNI;
    MEMBER PROCEDURE SETNOMBRE(NOMBRE VARCHAR2, APELLIDO VARCHAR2) AS
        BEGIN
        SELF.NOMBRE:=APELLIDO||', '||NOMBRE;
    END SETNOMBRE;
    MEMBER PROCEDURE SETNOMBRE(NOMBRE VARCHAR2) AS
        BEGIN
        SELF.NOMBRE:=NOMBRE;
    END SETNOMBRE;
    MEMBER PROCEDURE SETCALLE(CALLE VARCHAR2) AS
        BEGIN
        SELF.CALLE:=CALLE;
    END SETCALLE;
    MEMBER PROCEDURE SETPOBLACION(POBLACION VARCHAR2) AS
        BEGIN
        SELF.POBLACION:=POBLACION;
    END SETPOBLACION;
    MEMBER PROCEDURE SETPROVINCIA(PROVINCIA VARCHAR2) AS
        BEGIN
        SELF.PROVINCIA:=PROVINCIA;
    END SETPROVINCIA;
    MEMBER PROCEDURE SETFECHALTA(FECHA NUMBER) AS
        BEGIN
        SELF.FECHA_ALTA:=SYSDATE;
    END SETFECHALTA;
    MEMBER PROCEDURE SETFECHALTA(FECHA_ALTA DATE) AS
    BEGIN
        SELF.FECHA_ALTA:=FECHA_ALTA;
        END SETFECHALTA;
    END;


----- APARTADO 3
CREATE OR REPLACE TYPE SERVICIO AS OBJECT (
    IDSERVICIO NUMBER(5),
    REFCLIENTE REF CLIENTE,
    NRO_HORAS NUMBER(3),
    PRECIO_HORA NUMBER(5,2),
    FECHA_SERVICIO DATE,
    -- CONSTRUCTOR
    CONSTRUCTOR FUNCTION SERVICIO(IDSERVICIO NUMBER, REFCLIENTE REF CLIENTE, NRO_HORAS NUMBER, PRECIO_HORA NUMBER, FECHA_SERVICIO DATE)
            RETURN SELF AS RESULT,
    -- GETTER Y SETTER
    MEMBER FUNCTION GETIDSERVICIO RETURN NUMBER,
    MEMBER PROCEDURE SETIDSERVICIO(IDSERVICIO NUMBER),

    MEMBER FUNCTION GETREFCLIENTE RETURN REF CLIENTE,
    MEMBER PROCEDURE SETREFCLIENTE(REFCLIENTE REF CLIENTE),
 
    MEMBER FUNCTION GETNRO_HORAS RETURN NUMBER,
    MEMBER PROCEDURE SETNRO_HORAS(NRO_HORAS NUMBER),
 
    MEMBER FUNCTION GETPRECIO_HORA RETURN NUMBER,
    MEMBER PROCEDURE SETPRECIO_HORA(PRECIO_HORA NUMBER),
 
    MEMBER FUNCTION GETFECHA_SERVICIO RETURN DATE,
    MEMBER PROCEDURE SETFECHA_SERVICIO(FECHA_SERVICIO DATE)
) NOT FINAL;
    -- Creacion del body
CREATE OR REPLACE TYPE BODY SERVICIO AS
    -- CONSTRUCTOR
    CONSTRUCTOR FUNCTION SERVICIO(IDSERVICIO NUMBER, REFCLIENTE REF CLIENTE, NRO_HORAS NUMBER, PRECIO_HORA NUMBER, FECHA_SERVICIO DATE)
            RETURN SELF AS RESULT AS
        BEGIN
            SELF.SETIDSERVICIO(IDSERVICIO);
            SELF.SETREFCLIENTE(REFCLIENTE);
            SELF.SETNRO_HORAS(NRO_HORAS);
            SELF.SETPRECIO_HORA(PRECIO_HORA);
            SELF.SETFECHA_SERVICIO(FECHA_SERVICIO);
        RETURN;
    END SERVICIO;
    -- GETTER Y SETTER
    MEMBER FUNCTION GETIDSERVICIO RETURN NUMBER AS
        BEGIN
        RETURN SELF.IDSERVICIO;
    END GETIDSERVICIO;
    MEMBER PROCEDURE SETIDSERVICIO(IDSERVICIO NUMBER) AS
        BEGIN
        SELF.IDSERVICIO:=IDSERVICIO;
    END SETIDSERVICIO;
    MEMBER FUNCTION GETREFCLIENTE RETURN REF CLIENTE AS
        BEGIN
        RETURN SELF.REFCLIENTE;
    END GETREFCLIENTE;
    MEMBER PROCEDURE SETREFCLIENTE(REFCLIENTE REF CLIENTE) AS
        BEGIN
        SELF.REFCLIENTE:=REFCLIENTE;
    END SETREFCLIENTE;
    MEMBER FUNCTION GETNRO_HORAS RETURN NUMBER AS
        BEGIN
        RETURN SELF.NRO_HORAS;
    END GETNRO_HORAS;
    MEMBER PROCEDURE SETNRO_HORAS(NRO_HORAS NUMBER) AS
        BEGIN
        SELF.NRO_HORAS:=NRO_HORAS;
    END SETNRO_HORAS;
    MEMBER FUNCTION GETPRECIO_HORA RETURN NUMBER AS
        BEGIN
        RETURN SELF.PRECIO_HORA;
    END GETPRECIO_HORA;
    MEMBER PROCEDURE SETPRECIO_HORA(PRECIO_HORA NUMBER) AS
        BEGIN
        SELF.PRECIO_HORA:=PRECIO_HORA;
    END SETPRECIO_HORA;
    MEMBER FUNCTION GETFECHA_SERVICIO RETURN DATE AS
        BEGIN
        RETURN SELF.FECHA_SERVICIO;
    END GETFECHA_SERVICIO;
    MEMBER PROCEDURE SETFECHA_SERVICIO(FECHA_SERVICIO DATE) AS
        BEGIN
        SELF.FECHA_SERVICIO:=FECHA_SERVICIO;
    END SETFECHA_SERVICIO;
END;


----- APARTADO 4
CREATE TABLE CLIENTES_OBJ OF CLIENTE (PRIMARY KEY (IDCLIENTE));
INSERT INTO CLIENTES_OBJ VALUES(CLIENTE(1, '111111111A', 'MARÍA', 'LASO MAR', 'TOLEDO, 21-1º C', 'CIUDAD REAL', 'CIUDAD REAL' ));
INSERT INTO CLIENTES_OBJ VALUES(CLIENTE(2, '2222222B', 'MIRTA GIL, JUAN', 'COSO,10', 'DAIMIEL', 'CIUDAD REAL', TO_DATE('04/02/2021','DD/MM/YYYY') ));
INSERT INTO CLIENTES_OBJ VALUES(CLIENTE(3, '33333333C', 'TOSAR MESA, PEDRO', 'BARRIAL,10', 'ARGÉS', 'TOLEDO', TO_DATE('03/08/2020','DD/MM/YYYY') ));
COMMIT;


----- APARTADO 5
CREATE TABLE SERVICIOS_OBJ OF SERVICIO (PRIMARY KEY (IDSERVICIO));


----- APARTADO 6
DECLARE
    REFCLIENTE1 REF CLIENTE;
    REFCLIENTE2 REF CLIENTE;
    REFCLIENTE3 REF CLIENTE;
    p1 SERVICIO;
    CLIENTE_2 CLIENTE;
    SERVICIO_V SERVICIO;
BEGIN
    SELECT REF(u) INTO REFCLIENTE1 FROM CLIENTES_OBJ u WHERE u.IDCLIENTE = 1;
    p1 := NEW SERVICIO(11, REFCLIENTE1, 10, 30, TO_DATE('01/02/2022','DD/MM/YYYY'));
    INSERT INTO SERVICIOS_OBJ VALUES(p1);

    SELECT REF(u) INTO REFCLIENTE2 FROM CLIENTES_OBJ u WHERE u.IDCLIENTE = 2;
    INSERT INTO SERVICIOS_OBJ VALUES(22, REFCLIENTE2, 20, 40, TO_DATE('12/03/2022','DD/MM/YYYY'));

    SELECT VALUE(u) INTO CLIENTE_2 FROM CLIENTES_OBJ U WHERE U.IDCLIENTE = 2;
    CLIENTE_2.IDCLIENTE:=22;
    CLIENTE_2.DNI:= '21111111B';
    INSERT INTO CLIENTES_OBJ VALUES(CLIENTE_2);

    SELECT VALUE(u) INTO SERVICIO_V FROM SERVICIOS_OBJ U WHERE U.IDSERVICIO = 11;
    SERVICIO_V.IDSERVICIO:=12;
    SELECT REF(u) INTO REFCLIENTE3 FROM CLIENTES_OBJ u WHERE u.IDCLIENTE = 3;
    SERVICIO_V.REFCLIENTE:=REFCLIENTE3;
    INSERT INTO SERVICIOS_OBJ VALUES(SERVICIO_V);
END;


----- APARTADO 7
SELECT 
    IDSERVICIO "Id Servicio", 
    V.REFCLIENTE.NOMBRE "Nombre Cliente", 
    V.REFCLIENTE.DNI "DNI", 
    V.REFCLIENTE.POBLACION "Poblacion", 
    V.NRO_HORAS "Numero Horas", 
    V.PRECIO_HORA "Precio Horas",  
    (V.NRO_HORAS*V.PRECIO_HORA )"Total"
 FROM SERVICIOS_OBJ V;

